Init query plan page.
memgraph/documentation pull request #604
Opened 2024-03-20 13:15 UTC by antejavor

### Description

Please briefly explain the changes you made.

### Pull request type

Please check what kind of PR this is:

- [ ] Fix or improvement of an existing page
- [ ] New documentation page, release related

### Related PRs and issues

PR this doc page is related to: 
(especially necessary if the PR is related to a release)

Closes:
(paste the link to the issue it closes)

### Checklist:

- [ ] Check all content with Grammarly
- [ ] Perform a self-review of my code
- [ ] Make corresponding changes to the rest of the documentation (consult with the DX team)
- [ ] The build passes locally
- [ ] My changes generate no new warnings or errors
- [ ] Add a corresponding label
- [ ] If release-related, add a product and version label
- [ ] If release-related, add release note on product PR

2024-03-21 14:48 UTC, katarinasupe commented
I would put query plan page above performance optimizations in the sidebar

2024-03-26 12:38 UTC, antejavor commented
@kgolubic, I guess @matea16 and @katarinasupe will do a full content review. 

Just one thing @kgolubic , if you notice the deleted titles in this PR, they were deleted or changed. Should I update all the links? Or leave it to you? 

Just let me know (I am asking because I am not sure what you do after title changes etc.)

2024-03-26 12:57 UTC, kgolubic commented
> @kgolubic, I guess @matea16 and @katarinasupe will do a full content review.
> 
> Just one thing @kgolubic , if you notice the deleted titles in this PR, they were deleted or changed. Should I update all the links? Or leave it to you?
> 
> Just let me know (I am asking because I am not sure what you do after title changes etc.)

If you can, do a search for linked anchors, e.g.

![image](https://github.com/memgraph/documentation/assets/46486712/b3d994e3-511c-4b38-99e4-d7b15734b871)

If you don't have time for this, I can do it once PR is ready for shipping.

2024-03-26 12:59 UTC, matea16 approved these changes

2024-03-26 12:59 UTC, matea16 commented on pages/querying/query-plan.mdx
> +Query planner constructs an optimal execution plan and catches it.
```suggestion
Query planner constructs an optimal execution plan and caches it.
```

2024-03-26 12:59 UTC, matea16 commented on pages/querying/query-plan.mdx
> +It is sent to the database, and the first step it goes through is the **query
```suggestion
The query is sent to the database, and as the first step it goes through is the **query
```

2024-03-26 13:09 UTC, katarinasupe requested changes

2024-03-26 13:09 UTC, katarinasupe commented on pages/querying/performance-optimization.md
> +This time, the goal is to find the `:Transfer` node with the specific year property, and the `Filter` is applied to filter the results from `ScanALL,` again all nodes from the graph.
this part: "again all nodes from the graph".  is a bit weird. Can you rewrite that sentence so it's more clear?

2024-03-26 13:09 UTC, katarinasupe commented on pages/querying/performance-optimization.md
> +The query engine treats the following tripplet syntaxt  `(start node, edge, end node)` the same way:
```suggestion
The query engine treats the following triplet syntax `(start node, edge, end node)` the same way: 
```

2024-03-26 13:09 UTC, katarinasupe commented on pages/querying/performance-optimization.md
> +statements are different, and there is no uniqueness filter applied there since they are logically separated.
again a bit unclear, can you rewrite?

2024-03-26 13:09 UTC, katarinasupe commented on pages/querying/performance-optimization.md
> +When executing a query, Memgraph needs to decide where in the query graph to
"Memgraph needs to decide where in the query graph to"
This is unclear

2024-03-26 13:09 UTC, katarinasupe commented on pages/querying/performance-optimization.md
> +An example of selecting an index with USING INDEX:
```suggestion
An example of selecting an index with `USING INDEX`: 
```

2024-03-26 13:12 UTC, katarinasupe requested changes

2024-03-26 13:36 UTC, antejavor commented on pages/querying/query-plan.mdx
> -This means that any update of indexes or constraints (creation or deletion)
Nop

2024-03-26 13:36 UTC, antejavor commented on pages/querying/performance-optimization.md
> +This time, the goal is to find the `:Transfer` node with the specific year property, and the `Filter` is applied to filter the results from `ScanALL,` again all nodes from the graph.
I did.

2024-03-26 13:46 UTC, antejavor commented
@kgolubic I have updated the links.

2024-03-26 14:03 UTC, katarinasupe requested changes

2024-03-26 14:03 UTC, katarinasupe commented on pages/querying/performance-optimization.md
> +statements are considered independent, and there is no uniqueness filter applied there since they are logically separated query parts.
```suggestion
During parsing of a Cypher query, some clauses, such as multiple `MATCH` statements, split the query into multiple logical query parts. They are considered independent, so no uniqueness filter is applied.
```

2024-03-27 11:25 UTC, katarinasupe approved these changes

2024-03-27 12:13 UTC, kgolubic approved these changes
Everything looks ok.

2024-03-27 12:13 UTC, merged