Create a new page about experimental features
memgraph/documentation pull request #832
Opened 2024-06-07 11:21 UTC by kgolubic

### Description
 
- Created a new page about experimental features.
- Added links to the new page.

### Pull request type

Please check what kind of PR this is:

- [ ] New documentation page, release related

### Related PRs and issues

PR this doc page is related to: 
(especially necessary if the PR is related to a release)
https://github.com/memgraph/documentation/issues/812

Closes:
(paste the link to the issue it closes)

### Checklist:

- [ ] Check all content with Grammarly
- [ ] Perform a self-review of my code
- [ ] Make corresponding changes to the rest of the documentation (consult with the DX team)
- [ ] The build passes locally
- [ ] My changes generate no new warnings or errors
- [ ] Add a corresponding label
- [ ] If release-related, add a product and version label
- [ ] If release-related, add release note on product PR

2024-06-10 16:55 UTC, hal-eisen-MG requested changes
Left several comments

2024-06-11 14:39 UTC, gitbuda commented
This seems ok from the product perspective 😄 I think the statuses should be more accurate but we'll provide/update that before each release 😄

2024-06-12 11:27 UTC, kgolubic commented on pages/database-management/experimental-features.mdx
> +
I'll add a note about that.

2024-06-14 11:02 UTC, hal-eisen-MG commented on pages/database-management/experimental-features.mdx
> +description: Experimental features are new functionalities in Memgraph that carry some risk. They are still in development and may have stability issues.
Please add a phrase along the lines of "contact your support representative when encountering any challenges and we'll respond promptly to get you back on track quickly"

2024-06-14 11:04 UTC, hal-eisen-MG commented on pages/database-management/experimental-features.mdx
> +- **Description**: This feature enables high availability capabilities in Memgraph Enterprise Edition.
Avoid defining a term with itself: "high availability" in this case. I'd recommend something about "resilience" and/or "fault tolerance" here.

2024-06-14 11:06 UTC, hal-eisen-MG commented on pages/database-management/experimental-features.mdx
> +- **Description**: This feature enables authentication and multi-tenancy replication in Memgraph Enterprise Edition.
Avoid using a term to define itself. In this case, "replication" should be referring to headers and followers, along with a mention of the choice between sync and async, and perhaps a mention of horizontal scalability.

2024-06-14 11:11 UTC, hal-eisen-MG commented on pages/database-management/experimental-features.mdx
> +- **Description**: This feature enables text search capabilities within Memgraph. Text search only supports some usage modalities and is not guaranteed to work correctly in use cases involving concur
Avoid defining a term with itself. In this case, "text search" should explain the core concept of finding nodes based on property values, and mention the choice between literal and regex, and the aggregation concept.

2024-06-14 13:35 UTC, hal-eisen-MG approved these changes
LGTM

2024-06-14 14:42 UTC, merged