add callout for instance to be alive on force reset
memgraph/documentation pull request #877
Opened 2024-06-27 08:49 UTC by antoniofilipovic

### Description

Add docs for following PR:https://github.com/memgraph/memgraph/pull/2135

### Pull request type

Please check what kind of PR this is:

- [x] Fix or improvement of an existing page
- [ ] New documentation page, release related

### Related PRs and issues

PR this doc page is related to: 
(especially necessary if the PR is related to a release)

Closes:
[(paste the link to the issue it closes)](https://github.com/memgraph/memgraph/pull/2135)

### Checklist:

- [x] Check all content with Grammarly
- [x] Perform a self-review of my code
- [x] Make corresponding changes to the rest of the documentation (consult with the DX team)
- [x] The build passes locally
- [x] My changes generate no new warnings or errors
- [x] Add a corresponding label
- [x] If release-related, add a product and version label
- [x] If release-related, add release note on product PR

2024-06-27 13:06 UTC, kgolubic requested changes
Once the text is updated it will be good to go.

2024-06-27 13:06 UTC, kgolubic commented on pages/clustering/high-availability.mdx
> +</Callout>
Replace text in Callout with:

It is important to note that if an action fails and all instances are down, the leader will attempt to execute a force reset until one instance is promoted to MAIN. Until then, no other actions are allowed on the cluster.

Add one blank line above and below this text (within Callout tags).

2024-06-27 16:59 UTC, hal-eisen-MG approved these changes
LGTM

2024-07-01 10:51 UTC, kgolubic approved these changes
Everything looks OK.

2024-07-01 12:28 UTC, merged