HA: Data loss -> RPO
memgraph/documentation pull request #891
Opened 2024-07-04 07:41 UTC by as51340

### Description

In HA community a better term for data loss is recovery point objective. 

### Pull request type

Please check what kind of PR this is:

- [x] Fix or improvement of an existing page
- [ ] New documentation page, release related

### Related PRs and issues

PR this doc page is related to: 
(especially necessary if the PR is related to a release)

Closes:
(paste the link to the issue it closes)

### Checklist:

- [ ] Check all content with Grammarly
- [ ] Perform a self-review of my code
- [ ] Make corresponding changes to the rest of the documentation (consult with the DX team)
- [ ] The build passes locally
- [ ] My changes generate no new warnings or errors
- [ ] Add a corresponding label
- [ ] If release-related, add a product and version label
- [ ] If release-related, add release note on product PR

2024-07-04 08:16 UTC, kgolubic requested changes
Please update the sentence to be more user friendly.

2024-07-04 08:16 UTC, kgolubic commented on pages/clustering/high-availability.mdx
> +Under certain extreme scenarios, the current implementation of HA could lead to having Recovery Point Objective (RPO) != 0. These are environments with high volume of transactions
I know that this is a standard way, `RPO!=0`, but I suggest replacing notation with words. Something along the lines of: 

`Under certain extreme scenarios, the current implementation of High Availability (HA) could result in a Recovery Point Objective (RPO) greater than zero, meaning some data loss could occur.`

2024-07-05 09:26 UTC, as51340 commented
> Please update the sentence to be more user friendly.

Any advices?

2024-07-08 06:45 UTC, kgolubic commented
> > Please update the sentence to be more user friendly.
> 
> Any advices?

`Under certain extreme scenarios, the current implementation of High Availability (HA) could result in a Recovery Point Objective (RPO) greater than zero, meaning some data loss could occur.`

2024-07-17 22:21 UTC, hal-eisen-MG approved these changes
LGTM

2024-07-22 12:24 UTC, merged