Fix: Fix the query sharing page
memgraph/documentation pull request #928
Opened 2024-07-17 07:20 UTC by tonilastre

### Description

Fixes applied to the Query Sharing page from the issue: https://github.com/memgraph/documentation/issues/889

### Pull request type

Please check what kind of PR this is:

- [x] Fix or improvement of an existing page
- [ ] New documentation page, release related

### Related PRs and issues

PR this doc page is related to: 
Issue https://github.com/memgraph/documentation/issues/889

Closes:

Closes https://github.com/memgraph/documentation/issues/889

### Checklist:

- [ ] Check all content with Grammarly
- [ ] Perform a self-review of my code
- [ ] Make corresponding changes to the rest of the documentation (consult with the DX team)
- [ ] The build passes locally
- [ ] My changes generate no new warnings or errors
- [ ] Add a corresponding label
- [ ] If release-related, add a product and version label
- [ ] If release-related, add release note on product PR

2024-07-17 10:14 UTC, kgolubic approved these changes
Everything looks OK to me.

2024-07-17 21:16 UTC, hal-eisen-MG commented on pages/data-visualization/user-manual/query-sharing.mdx
> +non-SSL connections, just omit the optional environment variables:
Never use the word "just"

2024-07-18 10:00 UTC, tonilastre commented on pages/data-visualization/user-manual/query-sharing.mdx
> +non-SSL connections, just omit the optional environment variables:
```suggestion
non-SSL connections, omit the optional environment variables:
```

2024-07-18 21:14 UTC, hal-eisen-MG approved these changes
LGTM

2024-07-19 08:49 UTC, tonilastre commented
@katarinasupe can you also check if this solves all the issues you mentioned in the Issue?

2024-07-23 08:17 UTC, katarinasupe requested changes
- Fix title - it should be h1 (check GraphChat). 
- Use the same capitalization case across page (remove title case from the titles and use sentence-style capitalization; you can use title case for the feature name to keep it the same across the page)

Other than that, I love the new flow and all is clear now! :D

2024-07-23 08:17 UTC, katarinasupe commented on pages/data-visualization/user-manual/query-sharing.mdx
> +Query sharing requires a [valid Memgraph Enterprise license](/database-management/enabling-memgraph-enterprise).
```suggestion
Query sharing requires a [valid Memgraph Enterprise license](/database-management/enabling-memgraph-enterprise)
```

2024-07-23 08:17 UTC, katarinasupe commented on pages/data-visualization/user-manual/query-sharing.mdx
> +or a new Memgraph database in a multi-tenant environment.
Suggestion - link to sections below.

2024-07-23 08:17 UTC, katarinasupe commented on pages/data-visualization/user-manual/query-sharing.mdx
> +in your enterprise Memgraph instance. For better security, it
```suggestion
Let's say that you already created a new database called `lab`
in your enterprise Memgraph instance for remote storage. For better security, it
```

2024-07-23 22:45 UTC, hal-eisen-MG approved these changes
LGTM

2024-07-24 11:50 UTC, katarinasupe approved these changes

2024-07-24 13:56 UTC, merged